[package]
name = "blanc_os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "simple_boot",
]

[dependencies]
x86_64 = "0.14.4"

# Global Descriptor Table
gdt = { path = "crate/gdt" } 

# Interrupt Handler
interrupts = { path = "crate/interrupts" }

# Serial Printer
serial = { path = "crate/serial" }


[dependencies.bootloader]
version = "0.10.7"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
