[alias]
sbuild = "build --target shell.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
sasm = "rustc --target shell.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --emit asm"