[alias]
sbuild = "build --target do_nothing.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
sasm = "rustc --target do_nothing.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --emit asm"