[target.'cfg(target_os = "none")']
runner = "cargo run --package simple_boot --"



[alias]
kbuild = "build --target x86_64-rust-os.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem "
kimage = "run --target x86_64-rust-os.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-rust-os.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"

